# generated by penchant, environment: remote
source "https://rubygems.org"
gemspec
gem "rake"
gem "capybara"
gem "cucumber"
gem "rspec"
gem "cuke-pack", {:git=>"git://github.com/johnbintz/cuke-pack.git"}